name: Yarn publish

on:
  workflow_run:
    workflows: [Build and Test]
    types: [completed]
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies in react-components
      run: yarn install
    
    - name: Build package NPM package
      run: yarn build

    - name: Run npx semantic-release
      run: npx semantic-release
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}